exports.bodyTypes = [
  "Standard",
  "Cruiser",
  "Sport Bike",
  "Touring",
  "Scooter",
  "Moped",
  "Off-Road",
  "Other",
];
exports.conditions = ["Used", "New", "Rental", "Damaged", "For Parts", "Other"];
exports.fuelTypes = ["Petrol / Gasoline", "Electric", "Other"];
exports.colors = [
  "Biege",
  "Black",
  "Blue",
  "Brown",
  "Burgundy",
  "Gold",
  "Green",
  "Grey",
  "Off-White",
  "Orange",
  "Pink",
  "Purple",
  "Red",
  "Silver",
  "Tan",
  "Teal",
  "White",
  "Yellow",
  "Other",
];
exports.features = [
  "Electric start",
  "Alloy wheels",
  "Tubeless tyres",
  "Digital display panel",
  "Projected headlight",
  "Led tail light",
  "Front disc brake",
  "Rear disc brake",
  "Anti-lock braking system (ABS)",
  "Mono suspension",
  "Split seat",
  "Tripmeter",
];
exports.featuresDB = [
  "hasElectricStart",
  "hasAlloyWheels",
  "hasTubelessTyres",
  "hasDigitalDisplayPanel",
  "hasProjectedHeadLight",
  "hasLedTailLight",
  "hasFrontDiscBrake",
  "hasRearDiscBrake",
  "hasAbs",
  "hasMonoSuspension",
  "hasSplitSeat",
  "hasTripMeter",
];
