module.exports = [
  {
    key: 1,
    province: "Province 1",
    name: "",
    districts: [
      { district: "Taplejung", key: "0" },
      { district: "Sankhuwasabha", key: "1" },
      { district: "Solukhumbu", key: "2" },
      { district: "Okhaldhunga", key: "3" },
      { district: "Khotang", key: "4" },
      { district: "Bhojpur", key: "5" },
      { district: "Dhankuta", key: "6" },
      { district: "Terhathum", key: "7" },
      { district: "Panchthar", key: "8" },
      { district: "Ilam", key: "9" },
      { district: "Jhapa", key: "10" },
      { district: "Morang", key: "11" },
      { district: "Sunsari", key: "12" },
      { district: "Udayapur", key: "13" },
    ],
  },
  {
    key: 2,
    province: "Province 2",
    name: "",
    districts: [
      { district: "Saptari", key: "0" },
      { district: "Siraha", key: "1" },
      { district: "Dhanusa", key: "2" },
      { district: "Mahottari", key: "3" },
      { district: "Sarlahi", key: "4" },
      { district: "Rautahat", key: "5" },
      { district: "Bara", key: "6" },
      { district: "Parsa", key: "7" },
    ],
  },
  {
    key: 3,
    province: "Province 3",
    name: "Bagmati Pradesh",
    districts: [
      { district: "Dolakha", key: "0" },
      { district: "Sindhupalchok", key: "1" },
      { district: "Rasuwa", key: "2" },
      { district: "Dhading", key: "3" },
      { district: "Nuwakot", key: "4" },
      { district: "Kathmandu", key: "5" },
      { district: "Bhaktapur", key: "6" },
      { district: "Lalitpur", key: "7" },
      { district: "Kavrepalanchok", key: "8" },
      { district: "Ramechhap", key: "9" },
      { district: "Sindhuli", key: "10" },
      { district: "Makawanpur", key: "11" },
      { district: "Chitawan", key: "12" },
    ],
  },
  {
    key: 4,
    province: "Province 4",
    name: "Gandaki Pradesh",
    districts: [
      { district: "Gorkha", key: "0" },
      { district: "Manang", key: "1" },
      { district: "Mustang", key: "2" },
      { district: "Myagdi", key: "3" },
      { district: "Kaski", key: "4" },
      { district: "Lamjung", key: "5" },
      { district: "Tanahu", key: "6" },
      { district: "Nawalparasi East", key: "7" },
      { district: "Syangja", key: "8" },
      { district: "Parbat", key: "9" },
      { district: "Baglung", key: "10" },
    ],
  },
  {
    key: 5,
    province: "Province 5",
    name: "",
    districts: [
      { district: "Rukum East", key: "0" },
      { district: "Rolpa", key: "1" },
      { district: "Pyuthan", key: "2" },
      { district: "Gulmi", key: "3" },
      { district: "Arghakhanchi", key: "4" },
      { district: "Palpa", key: "5" },
      { district: "Nawalparasi West", key: "6" },
      { district: "Rupandehi", key: "7" },
      { district: "Kapilbastu", key: "8" },
      { district: "Dang", key: "9" },
      { district: "Banke", key: "10" },
      { district: "Bardiya", key: "11" },
    ],
  },
  {
    key: 6,
    province: "Province 6",
    name: "Karnali Pradesh",
    districts: [
      { district: "Dolpa", key: "0" },
      { district: "Mugu", key: "1" },
      { district: "Humla", key: "2" },
      { district: "Jumla", key: "3" },
      { district: "Kalikot", key: "4" },
      { district: "Dailekh", key: "5" },
      { district: "Jajarkot", key: "6" },
      { district: "Rukum West", key: "7" },
      { district: "Salyan", key: "8" },
      { district: "Surkhet", key: "9" },
    ],
  },
  {
    key: 7,
    province: "Province 7",
    name: "Sudarpashim Pradesh",
    districts: [
      { district: "Bajura", key: "0" },
      { district: "Bajhang", key: "1" },
      { district: "Darchula", key: "2" },
      { district: "Baitadi", key: "3" },
      { district: "Dadeldhura", key: "4" },
      { district: "Doti", key: "5" },
      { district: "Achham", key: "6" },
      { district: "Kailali", key: "7" },
      { district: "Kanchanpur", key: "8" },
    ],
  },
];
